server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/document_db
    username: root
    password: 12345		
claim-service:
  url: http://localhost:8081



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

file:
  upload-dir: C:/claimswift/uploads
  max-size: 5MB

jwt:
  secret: 12345678901234567890123456789012345678901234567890