server:
  port: 8084

payment:
  base-url: http://localhost:8083

claim:
  base-url: http://localhost:8081/api/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/assessment_db
    username: root
    password: shlok123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect